services:
  api:
    container_name: express-api
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${PORT}
    networks:
      - atividade-express-network
      
  db:
    container_name: express-db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - atividade-express-network
    volumes: 
     - "postgres_data:/var/lib/postgresql/data"

  adminer:
    container_name: express-adminer
    image: adminer
    ports:
      - 8000:8080
    networks:
      - atividade-express-network

networks:
  atividade-express-network:
    driver: bridge

volumes: 
  postgres_data:
